### Create Article
POST localhost:8080/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMzNjQwODUsImlkIjo1LCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzNDUwNDg1LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.bqOSm02AAf53rDj0eE4bs0acBtSxtjFa9ss1a-bcXxRR-TnWg8MU6FeuKdY7ysf-4TVbzY735et14NeZtgMOSg
Content-Type:  application/json

{
  "title": "mmm",
  "description": "ndjde",
  "content": "Bsdffdafdasfdgfgfarfgfd",
  "sharedCount": 5,
  "categoryId": 3,
  "regionId": 3,
  "moderatorId": 3,
  "articleTypeId": 1
}

### Update Article
PUT localhost:8080/api/v1/article/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MzU2NTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMjIwNTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.XGajYE-pa593y21eRvncJx3KvDDGWVdfbtb4t2B8paloLZWZ4lIyiFZJS7N-Q7IxUKaCnJV-K0ILBjABNj5iQw
Content-Type:  application/json

{
  "id": "67c59e28-dc54-4f08-af65-88eb2387dcc3",
  "title": "Allanima6",
  "description": "Qisqacha Allanima6",
  "content": "Bir bor ekan bir yoq ekan6",
  "sharedCount": 6,
  "categoryId": 2,
  "regionId": 2,
  "moderatorId": 2,
  "articleTypeId": 1
}
### ChangeStatus Article
PUT localhost:8080/api/v1/article/changeStatus/67c59e28-dc54-4f08-af65-88eb2387dcc3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MzU2NTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMjIwNTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.XGajYE-pa593y21eRvncJx3KvDDGWVdfbtb4t2B8paloLZWZ4lIyiFZJS7N-Q7IxUKaCnJV-K0ILBjABNj5iQw
Content-Type:  application/json

### Delete Article
PUT localhost:8080/api/v1/article/delete/a0783608-31c6-4418-af76-e6f84227d9db
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5MzU2NTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwMjIwNTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.XGajYE-pa593y21eRvncJx3KvDDGWVdfbtb4t2B8paloLZWZ4lIyiFZJS7N-Q7IxUKaCnJV-K0ILBjABNj5iQw
Content-Type:  application/json

### Get 5 Article
GET localhost:8080/api/v1/article/getLastFiveArticleByType/1

### Get 3 Article
GET localhost:8080/api/v1/article/getLastThreeArticleByType/1