### Login
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
  "email": "adminjon@gmail.com",
  "password": "123321"
}

### Auth
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Ketmon ",
  "email": "ketmon@mail.ru",
  "phone": "1",
  "password": "1",
  "role": "ADMIN"
}
