### Login
POST localhost:8081/api/v1/auth/login
Content-Type:  application/json

{
  "email": "mol@gmail.com",
  "password": "000"
}

### Auth
POST localhost:8081/api/v1/auth/register
Content-Type:  application/json

{
  "name": "mol ",
  "email": "mol@mail.ru",
  "phone": "000",
  "password": "000",
  "password": "000",
  "role": "ADMIN"
}
