### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "aliyev@mail.ru",
  "password": "5432"
}

### Auth
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Venom",
  "email": "venom@mail.ru",
  "phone": "7777",
  "password": "1111",
  "role": "ADMIN"
}
