### Create Category
POST localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIwODY0MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIxNzI4MjgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1M95AXImNj91615YCGyvIBZtdHXV_9hgC5RBA-ScctkNrMHzeZzJPIWdaH9MZfDJ0hwUZwWN7eZcjLi1ZliDIQ
Content-Type:  application/json

//{
//  "nameUz": "Mahalliy",
//  "nameRu": "Местный",
//  "nameEng": "Local",
//  "visible": true
//}
//{
//  "nameUz": "Jahon",
//  "nameRu": "МИР",
//  "nameEng": "World",
//  "visible": true
//}
//{
//  "nameUz": "IQTISODIYOT",
//  "nameRu": "ЭКОНОМИКА",
//  "nameEng": "ECONOMY",
//  "visible": true
//}
{
  "nameUz": "FAN-TEXNIKA",
  "nameRu": "НАУКА И ТЕХНОЛОГИЯ",
  "nameEng": "SCIENCE AND TECHNOLOGY",
  "visible": true
}
### Update Category
PUT localhost:8080/api/v1/category/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIwODY0MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIxNzI4MjgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1M95AXImNj91615YCGyvIBZtdHXV_9hgC5RBA-ScctkNrMHzeZzJPIWdaH9MZfDJ0hwUZwWN7eZcjLi1ZliDIQ
Content-Type:  application/json

{
  "id" : 1,
  "nameUz": "SPORT",
  "nameRu": "ВИДЫ СПОРТА",
  "nameEng": "SPORTS",
  "visible": true
}

### List Category
PUT localhost:8080/api/v1/category/delete/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIwODY0MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIxNzI4MjgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1M95AXImNj91615YCGyvIBZtdHXV_9hgC5RBA-ScctkNrMHzeZzJPIWdaH9MZfDJ0hwUZwWN7eZcjLi1ZliDIQ
Content-Type:  application/json

### Paging Category
PUT localhost:8080/api/v1/category/paging
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIwODY0MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIxNzI4MjgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1M95AXImNj91615YCGyvIBZtdHXV_9hgC5RBA-ScctkNrMHzeZzJPIWdaH9MZfDJ0hwUZwWN7eZcjLi1ZliDIQ
Content-Type:  application/json

### GetByLang Category
PUT localhost:8080/api/v1/category/getByLang/Uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIwODY0MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIxNzI4MjgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1M95AXImNj91615YCGyvIBZtdHXV_9hgC5RBA-ScctkNrMHzeZzJPIWdaH9MZfDJ0hwUZwWN7eZcjLi1ZliDIQ
Content-Type:  application/json