### Create profile
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NzEzMzIsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTc3MzIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.T4wEYXxTqq3K5Na2j1Kg4xOuFtpYYlT_4ifLVEmKrRd4iyQ3gKjbFQA6RRjE5VaUbUo0SVIg7vkyYDnNsS-GmQ
Content-Type:  application/json

{
  "name": "Venom",
  "surname": "Venom",
  "email": "venom@mail.ru",
  "phone": "4321",
  "password": "7777",
  "role": "ADMIN"
}

### Update profile
PUT localhost:8080/api/v1/profile/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NzEzMzIsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNTc3MzIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.T4wEYXxTqq3K5Na2j1Kg4xOuFtpYYlT_4ifLVEmKrRd4iyQ3gKjbFQA6RRjE5VaUbUo0SVIg7vkyYDnNsS-GmQ
Content-Type:  application/json

{
  "name": "MAzgi",
  "surname": "mazgiyev",
  "email": "mazgi@mail.ru",
  "phone": "0000",
  "password": "2443",
  "role": "PUBLISHER"
}

### Update profile
PUT localhost:8080/api/v1/profile/updatedetail/6
Content-Type:  application/json

{
  "name": "Mazgi",
  "surname": "mazgiyev",
  "email": "mazgi@mail.ru",
  "phone": "6543",
  "password": "2443",
  "role": "PUBLISHER"
}